### ISSUE TITLE
Why is filesize a String?

### ISSUE THREAD

**Issue by sourcesmith** [thomas-ayling/amcr-back-end#15]
https://github.com/thomas-ayling/amcr-back-end/blob/3d82e36419ba14a120b080732f080a71fbf1a88c/src/main/java/com/globallogic/amcr/model/Attachment.java#L49

**Comment by thomas-ayling** [comment]
File size is a string as I  convert the number of bytes into a more readable format, so 5MB instead of 5242880 bytes.
