### ISSUE TITLE
Services are typically implemented as an interface with a separate implementation

### ISSUE THREAD

**Issue by sourcesmith** [thomas-ayling/amcr-back-end#16]
https://github.com/thomas-ayling/amcr-back-end/blob/3d82e36419ba14a120b080732f080a71fbf1a88c/src/main/java/com/globallogic/amcr/service/EmailService.java#L24

Makes mocking easier for starters.

**Comment by thomas-ayling** [comment]
Would it be a case of creating a separate interface for each service as they have differing methods?

**Comment by thomas-ayling** [comment]
Will work on implementing this, just curious as to why it's necessary
