### ISSUE TITLE
No delay on retries

### ISSUE THREAD

**Issue by sourcesmith** [thomas-ayling/amcr-back-end#17]
https://github.com/thomas-ayling/amcr-back-end/blob/3d82e36419ba14a120b080732f080a71fbf1a88c/src/main/java/com/globallogic/amcr/service/EmailService.java#L45

Typically retries use an exponential backoff.  Hammer the retries as fast a possible often does not result in a different outcome and may actually be considered bad behaviour by some services.

**Comment by thomas-ayling** [comment]
Would an implementation like this work alright for the use case?
https://www.baeldung.com/resilience4j-backoff-jitter
