### ISSUE TITLE
Externalise env sensitive config

### ISSUE THREAD

**Issue by sourcesmith** [thomas-ayling/amcr-back-end#3]
https://github.com/thomas-ayling/amcr-back-end/blob/fc62074fdd4fee0bc98de7b1fb363e27286da3c1/src/main/resources/application.properties#L10

Properties referencing endpoints, hostnames, etc. and credentials should be externalised to they can be set per env.  The property placeholders can specify defaults for convenience when developing locally.

**Comment by thomas-ayling** [comment]
After speaking to Andy it seems like we don't have the facilities for externalising variables in the AWS server as of yet
