### ISSUE TITLE
No docs so not clear what this is.

### ISSUE THREAD

**Issue by sourcesmith** [thomas-ayling/amcr-back-end#7]
https://github.com/thomas-ayling/amcr-back-end/blob/fc62074fdd4fee0bc98de7b1fb363e27286da3c1/src/main/java/com/globallogic/amcr/payload/FeedbackResponse.java#L30

**Comment by thomas-ayling** [comment]
What docs are expected and where should they be saved in the repo? I have an ERD on the Jira board that needs updating so will work on updating that

**Comment by thomas-ayling** [comment]
Thanks, yeah I've used them before will implement now. Do you expect to see them on each class?
