### ISSUE TITLE
Some of these properties must be required

### ISSUE THREAD

**Issue by sourcesmith** [thomas-ayling/amcr-back-end#8]
https://github.com/thomas-ayling/amcr-back-end/blob/3d82e36419ba14a120b080732f080a71fbf1a88c/src/main/java/com/globallogic/amcr/model/Attachment.java#L15

Some of the properties must presumably required but there are not assertions as such in the constructor or appropriate setters.  Properties that are permitted to be null are not documented as such.

**Comment by thomas-ayling** [comment]
Would this be implemented with an annotation?
